"""transactions on display

Revision ID: 10d0e433d736
Revises: 49b993537e3c
Create Date: 2026-10-09 09:29:50.610645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10d0e433d736'
down_revision: Union[str, Sequence[str], None] = '49b993537e3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expenses',
    sa.Column('expense_id', sa.UUID(), nullable=False),
    sa.Column('expense_number', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('category', sa.Enum('KITCHEN_INGREDIENTS', 'BEVERAGES_STOCK', 'UTILITIES', 'STAFF_WAGES', 'PACKAGING_SUPPLIES', 'MAINTENANCE_REPAIRS', 'MARKETING', 'OTHER', name='expensecategory'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('payment_reference', sa.String(length=150), nullable=True),
    sa.Column('vendor_name', sa.String(length=150), nullable=True),
    sa.Column('receipt_url', sa.String(length=500), nullable=True),
    sa.Column('recorded_by_admin_id', sa.UUID(), nullable=True),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['recorded_by_admin_id'], ['admins.admin_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('expense_id')
    )
    op.create_index(op.f('ix_expenses_category'), 'expenses', ['category'], unique=False)
    op.create_index(op.f('ix_expenses_expense_date'), 'expenses', ['expense_date'], unique=False)
    op.create_index(op.f('ix_expenses_expense_number'), 'expenses', ['expense_number'], unique=True)
    op.create_index(op.f('ix_expenses_recorded_by_admin_id'), 'expenses', ['recorded_by_admin_id'], unique=False)
    op.create_table('transactions',
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('reference_number', sa.String(length=30), nullable=False),
    sa.Column('transaction_type', sa.Enum('INCOME', 'EXPENSE', 'REFUND', 'PAYOUT', name='transactiontype'), nullable=False),
    sa.Column('category', sa.Enum('FOOD_SALES', 'BEVERAGE_SALES', 'CATERING_SALES', 'KITCHEN_PROCUREMENT', 'STAFF_WAGES', 'UTILITIES', 'MAINTENANCE', 'PACKAGING', 'MARKETING', 'OTHER', name='transactioncategory'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('payment_reference', sa.String(length=150), nullable=True),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('expense_id', sa.UUID(), nullable=True),
    sa.Column('recorded_by_admin_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['expense_id'], ['expenses.expense_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recorded_by_admin_id'], ['admins.admin_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_index(op.f('ix_transactions_category'), 'transactions', ['category'], unique=False)
    op.create_index(op.f('ix_transactions_created_at'), 'transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_transactions_expense_id'), 'transactions', ['expense_id'], unique=False)
    op.create_index(op.f('ix_transactions_order_id'), 'transactions', ['order_id'], unique=False)
    op.create_index(op.f('ix_transactions_payment_reference'), 'transactions', ['payment_reference'], unique=False)
    op.create_index(op.f('ix_transactions_recorded_by_admin_id'), 'transactions', ['recorded_by_admin_id'], unique=False)
    op.create_index(op.f('ix_transactions_reference_number'), 'transactions', ['reference_number'], unique=True)
    op.create_index(op.f('ix_transactions_transaction_type'), 'transactions', ['transaction_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_transaction_type'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_reference_number'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_recorded_by_admin_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_payment_reference'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_order_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_expense_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_created_at'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_category'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_expenses_recorded_by_admin_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_expense_number'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_expense_date'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_category'), table_name='expenses')
    op.drop_table('expenses')
    # ### end Alembic commands ###
