"""Initial schema: oasis platform

Revision ID: 49b993537e3c
Revises: 
Create Date: 2026-10-09 06:35:02.350986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49b993537e3c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('admin_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hashed', sa.String(), nullable=False),
    sa.Column('firstname', sa.String(length=100), nullable=False),
    sa.Column('lastname', sa.String(length=100), nullable=False),
    sa.Column('other_name', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'ADMIN', 'USER', name='adminrole'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'SUSPENDED', name='adminstatus'), nullable=False),
    sa.Column('privileges', sa.JSON(), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('admin_id')
    )
    op.create_index(op.f('ix_admins_email'), 'admins', ['email'], unique=True)
    op.create_index(op.f('ix_admins_phone'), 'admins', ['phone'], unique=False)
    op.create_index(op.f('ix_admins_role'), 'admins', ['role'], unique=False)
    op.create_index(op.f('ix_admins_status'), 'admins', ['status'], unique=False)
    op.create_table('categories',
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon_name', sa.String(length=50), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=True)
    op.create_table('contact_inquiries',
    sa.Column('inquiry_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('subject', sa.String(length=200), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('UNREAD', 'RESPONDED', 'ARCHIVED', name='inquirystatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('inquiry_id')
    )
    op.create_table('customers',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hashed', sa.String(), nullable=False),
    sa.Column('firstname', sa.String(length=100), nullable=False),
    sa.Column('lastname', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('delivery_address', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('customer_id')
    )
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=True)
    op.create_index(op.f('ix_customers_phone'), 'customers', ['phone'], unique=False)
    op.create_table('promotions',
    sa.Column('promo_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('discount_type', sa.String(length=20), nullable=False),
    sa.Column('discount_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('min_order_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('times_used', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('promo_id')
    )
    op.create_index(op.f('ix_promotions_code'), 'promotions', ['code'], unique=True)
    op.create_index(op.f('ix_promotions_is_active'), 'promotions', ['is_active'], unique=False)
    op.create_table('seating_areas',
    sa.Column('seating_area_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('location', sa.String(length=150), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('media', sa.JSON(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('seating_area_id')
    )
    op.create_index(op.f('ix_seating_areas_slug'), 'seating_areas', ['slug'], unique=True)
    op.create_table('dishes',
    sa.Column('dish_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('subtitle', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('calories', sa.Integer(), nullable=True),
    sa.Column('prep_time_minutes', sa.Integer(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('allergens', sa.JSON(), nullable=True),
    sa.Column('wine_pairing', sa.String(length=150), nullable=True),
    sa.Column('is_popular', sa.Boolean(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.category_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('dish_id')
    )
    op.create_index(op.f('ix_dishes_category_id'), 'dishes', ['category_id'], unique=False)
    op.create_index(op.f('ix_dishes_is_available'), 'dishes', ['is_available'], unique=False)
    op.create_index(op.f('ix_dishes_is_popular'), 'dishes', ['is_popular'], unique=False)
    op.create_index(op.f('ix_dishes_name'), 'dishes', ['name'], unique=False)
    op.create_index(op.f('ix_dishes_slug'), 'dishes', ['slug'], unique=True)
    op.create_table('orders',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('order_number', sa.String(length=30), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('served_by_admin_id', sa.UUID(), nullable=True),
    sa.Column('customer_name', sa.String(length=150), nullable=True),
    sa.Column('customer_email', sa.String(length=255), nullable=True),
    sa.Column('customer_phone', sa.String(length=50), nullable=True),
    sa.Column('order_type', sa.Enum('DELIVERY', 'PICKUP', 'DINE_IN', name='ordertype'), nullable=False),
    sa.Column('delivery_address', sa.Text(), nullable=True),
    sa.Column('order_status', sa.Enum('PENDING', 'CONFIRMED', 'PREPARING', 'READY', 'OUT_FOR_DELIVERY', 'DELIVERED', 'CANCELLED', name='orderstatus'), nullable=False),
    sa.Column('payment_status', sa.Enum('PENDING', 'PAID', 'FAILED', 'REFUNDED', name='paymentstatus'), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('payment_reference', sa.String(length=150), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('promo_code', sa.String(length=50), nullable=True),
    sa.Column('tax', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('delivery_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['served_by_admin_id'], ['admins.admin_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_index(op.f('ix_orders_customer_email'), 'orders', ['customer_email'], unique=False)
    op.create_index(op.f('ix_orders_customer_id'), 'orders', ['customer_id'], unique=False)
    op.create_index(op.f('ix_orders_order_number'), 'orders', ['order_number'], unique=True)
    op.create_index(op.f('ix_orders_order_status'), 'orders', ['order_status'], unique=False)
    op.create_index(op.f('ix_orders_payment_reference'), 'orders', ['payment_reference'], unique=False)
    op.create_index(op.f('ix_orders_payment_status'), 'orders', ['payment_status'], unique=False)
    op.create_index(op.f('ix_orders_served_by_admin_id'), 'orders', ['served_by_admin_id'], unique=False)
    op.create_table('reservations',
    sa.Column('reservation_id', sa.UUID(), nullable=False),
    sa.Column('reference_code', sa.String(length=20), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('assigned_admin_id', sa.UUID(), nullable=True),
    sa.Column('seating_area_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('reservation_date', sa.Date(), nullable=False),
    sa.Column('reservation_time', sa.Time(), nullable=False),
    sa.Column('guests_count', sa.Integer(), nullable=False),
    sa.Column('special_requests', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'SEATED', 'COMPLETED', 'CANCELLED', 'NO_SHOW', name='reservationstatus'), nullable=False),
    sa.Column('table_number', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_admin_id'], ['admins.admin_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['seating_area_id'], ['seating_areas.seating_area_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('reservation_id')
    )
    op.create_index(op.f('ix_reservations_email'), 'reservations', ['email'], unique=False)
    op.create_index(op.f('ix_reservations_reference_code'), 'reservations', ['reference_code'], unique=True)
    op.create_index(op.f('ix_reservations_reservation_date'), 'reservations', ['reservation_date'], unique=False)
    op.create_table('dish_media',
    sa.Column('media_id', sa.UUID(), nullable=False),
    sa.Column('dish_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('media_url', sa.String(length=500), nullable=False),
    sa.Column('media_type', sa.Enum('IMAGE', 'VIDEO', name='mediatype'), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['dish_id'], ['dishes.dish_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('media_id')
    )
    op.create_index(op.f('ix_dish_media_dish_id'), 'dish_media', ['dish_id'], unique=False)
    op.create_index(op.f('ix_dish_media_is_primary'), 'dish_media', ['is_primary'], unique=False)
    op.create_table('order_items',
    sa.Column('order_item_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('dish_id', sa.UUID(), nullable=False),
    sa.Column('dish_name', sa.String(length=150), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('special_requests', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['dish_id'], ['dishes.dish_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('order_item_id')
    )
    op.create_index(op.f('ix_order_items_dish_id'), 'order_items', ['dish_id'], unique=False)
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.create_table('reviews',
    sa.Column('review_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('dish_id', sa.UUID(), nullable=True),
    sa.Column('author_name', sa.String(length=100), nullable=False),
    sa.Column('author_location', sa.String(length=100), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('quote', sa.Text(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dish_id'], ['dishes.dish_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('review_id')
    )
    op.create_index(op.f('ix_reviews_is_approved'), 'reviews', ['is_approved'], unique=False)
    op.create_index(op.f('ix_reviews_is_featured'), 'reviews', ['is_featured'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviews_is_featured'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_is_approved'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_dish_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_dish_media_is_primary'), table_name='dish_media')
    op.drop_index(op.f('ix_dish_media_dish_id'), table_name='dish_media')
    op.drop_table('dish_media')
    op.drop_index(op.f('ix_reservations_reservation_date'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_reference_code'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_email'), table_name='reservations')
    op.drop_table('reservations')
    op.drop_index(op.f('ix_orders_served_by_admin_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_payment_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_payment_reference'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_number'), table_name='orders')
    op.drop_index(op.f('ix_orders_customer_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_customer_email'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_dishes_slug'), table_name='dishes')
    op.drop_index(op.f('ix_dishes_name'), table_name='dishes')
    op.drop_index(op.f('ix_dishes_is_popular'), table_name='dishes')
    op.drop_index(op.f('ix_dishes_is_available'), table_name='dishes')
    op.drop_index(op.f('ix_dishes_category_id'), table_name='dishes')
    op.drop_table('dishes')
    op.drop_index(op.f('ix_seating_areas_slug'), table_name='seating_areas')
    op.drop_table('seating_areas')
    op.drop_index(op.f('ix_promotions_is_active'), table_name='promotions')
    op.drop_index(op.f('ix_promotions_code'), table_name='promotions')
    op.drop_table('promotions')
    op.drop_index(op.f('ix_customers_phone'), table_name='customers')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.drop_table('customers')
    op.drop_table('contact_inquiries')
    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_admins_status'), table_name='admins')
    op.drop_index(op.f('ix_admins_role'), table_name='admins')
    op.drop_index(op.f('ix_admins_phone'), table_name='admins')
    op.drop_index(op.f('ix_admins_email'), table_name='admins')
    op.drop_table('admins')
    # ### end Alembic commands ###
