"""admin notifications

Revision ID: a66560e4985a
Revises: 10d0e433d736
Create Date: 2026-10-09 14:09:33.917982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a66560e4985a'
down_revision: Union[str, Sequence[str], None] = '10d0e433d736'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_notifications',
    sa.Column('notification_id', sa.UUID(), nullable=False),
    sa.Column('notification_type', sa.Enum('ORDER', 'RESERVATION', 'SYSTEM', name='notificationtype'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('reference_id', sa.String(length=100), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('notification_id')
    )
    op.create_index(op.f('ix_admin_notifications_created_at'), 'admin_notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_admin_notifications_is_read'), 'admin_notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_admin_notifications_notification_type'), 'admin_notifications', ['notification_type'], unique=False)
    op.create_index(op.f('ix_admin_notifications_reference_id'), 'admin_notifications', ['reference_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admin_notifications_reference_id'), table_name='admin_notifications')
    op.drop_index(op.f('ix_admin_notifications_notification_type'), table_name='admin_notifications')
    op.drop_index(op.f('ix_admin_notifications_is_read'), table_name='admin_notifications')
    op.drop_index(op.f('ix_admin_notifications_created_at'), table_name='admin_notifications')
    op.drop_table('admin_notifications')
    # ### end Alembic commands ###
